In [7]:
import pandas as pd
import numpy as np

from io import StringIO

from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [8]:
data = """price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
"""

df = pd.read_csv(StringIO(data))
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished

In [9]:
df['price_per_sqft'] = df['price'] / df['area']
df[['price', 'area', 'price_per_sqft']]

      price  area  price_per_sqft
0  13300000  7420      1792.45283

In [10]:
categorical_cols = [
    'mainroad', 'guestroom', 'basement',
    'hotwaterheating', 'airconditioning',
    'prefarea', 'furnishingstatus'
]

encoder = LabelEncoder()
for col in categorical_cols:
    df[col] = encoder.fit_transform(df[col])

df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,0,0,0,0,0,2,0,0,1792.45283

In [11]:
X = df.drop('price', axis=1)
y = df['price']

In [12]:
lin_model = LinearRegression()
lin_model.fit(X, y)

LinearRegression()

In [13]:
feature_importance_lr = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lin_model.coef_
})

feature_importance_lr

             Feature  Coefficient
0               area          0.0
1           bedrooms          0.0
2          bathrooms          0.0
3            stories          0.0
4           mainroad          0.0
5          guestroom          0.0
6           basement          0.0
7    hotwaterheating          0.0
8    airconditioning          0.0
9            parking          0.0
10          prefarea          0.0
11  furnishingstatus          0.0
12    price_per_sqft          0.0

In [14]:
tree_model = DecisionTreeRegressor(random_state=42)
tree_model.fit(X, y)

DecisionTreeRegressor(random_state=42)

In [15]:
feature_importance_tree = pd.DataFrame({
    'Feature': X.columns,
    'Importance': tree_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

feature_importance_tree

             Feature  Importance
0               area         0.0
1           bedrooms         0.0
2          bathrooms         0.0
3            stories         0.0
4           mainroad         0.0
5          guestroom         0.0
6           basement         0.0
7    hotwaterheating         0.0
8    airconditioning         0.0
9            parking         0.0
10          prefarea         0.0
11  furnishingstatus         0.0
12    price_per_sqft         0.0

In [16]:
print("Summary:")
print("1. Created price_per_sqft as a new feature.")
print("2. Encoded categorical variables using Label Encoding.")
print("3. Used Linear Regression and Decision Tree to analyze feature importance.")
print("4. Decision Tree importance shows relative contribution of each feature.")

Summary:
1. Created price_per_sqft as a new feature.
2. Encoded categorical variables using Label Encoding.
3. Used Linear Regression and Decision Tree to analyze feature importance.
4. Decision Tree importance shows relative contribution of each feature.